### PR TITLE
Test Typecheck in GitHub action and Upgrade to Remix 2.1.0

### PR DESCRIPTION
**Pull request by shami-dev**
Issue: 

## Summary (1-2 sentences)
- Test check.yml file for checking types within GitHub Actions. 
- Upgrading Remix 2.0.0 -> 2.1.0. It allowed to get rid of "Jsonify Type" errors. 

## Commands
```
npx upgrade-remix
```
## Sources
About the Remix 2.1.0 minor upgrade: https://github.com/remix-run/remix/releases

## Co-authors: 
@tonydangblog, Tony Dang
@eiffelwong1, Sing Wong

### CODE REVIEW

**Review by tonydangblog — APPROVED** [review]

**Review by eiffelwong1 — APPROVED** [review]
approval, need remix update in future

**Comment by andrelandgraf** [comment]
Well, it is working! 🥳 

I guess we need to include the fixes for these errors in this PR:

```txt
app/routes/_auth.login.tsx(109,39): error TS2339: Property 'message' does not exist on type 'never'.
app/routes/_auth.login.tsx(10[9](https://github.com/social-plan-it/plan-it-social-web/actions/runs/6525580264/job/17718408424?pr=75#step:5:10),90): error TS2339: Property 'message' does not exist on type 'never'.
app/routes/groups_.$groupId.tsx(17,12): error TS18047: 'data' is possibly 'null'.
app/routes/groups_.$groupId.tsx(17,17): error TS2339: Property 'group' does not exist on type 'JsonifyObject<{}> | JsonifyObject<{ readonly type: ResponseType; readonly url: string; readonly body: ReadableStream<Uint8Array> | null; ... 5 more ...; readonly bodyUsed: boolean; }>'.
  Property 'group' does not exist on type 'JsonifyObject<{}>'.
app/routes/groups_.$groupId.tsx(18,[11](https://github.com/social-plan-it/plan-it-social-web/actions/runs/6525580264/job/17718408424?pr=75#step:5:12)): error TS18047: 'data' is possibly 'null'.
app/routes/groups_.$groupId.tsx(18,16): error TS2339: Property 'group' does not exist on type 'JsonifyObject<{}> | JsonifyObject<{ readonly type: ResponseType; readonly url: string; readonly body: ReadableStream<Uint8Array> | null; ... 5 more ...; readonly bodyUsed: boolean; }>'.
  Property 'group' does not exist on type 'JsonifyObject<{}>'.
app/routes/search.tsx(28,11): error TS2339: Property 'events' does not exist on type 'JsonifyObject<{}> | JsonifyObject<{ readonly type: ResponseType; readonly url: string; readonly body: ReadableStream<Uint8Array> | null; ... 5 more ...; readonly bodyUsed: boolean; }> | null'.
app/routes/search.tsx(28,19): error TS2339: Property 'query' does not exist on type 'JsonifyObject<{}> | JsonifyObject<{ readonly type: ResponseType; readonly url: string; readonly body: ReadableStream<Uint8Array> | null; ... 5 more ...; readonly bodyUsed: boolean; }> | null'.
Error: Process completed with exit code 2.
```

**Comment by andrelandgraf** [comment]
Update! I found the job name ("build") of our GitHub action workflow in the `main` branch status checks! You can now no longer merge if the `build` workflow fails! 🥳

**Review by tonydangblog — APPROVED** [review]
LGTM! Lets get it merged!

**Pull request merged**
